  version: '3.7'

  services:
    db:
      image: postgres:12-alpine
      env_file:
        - ./.env
      ports:
        - "5432:5432"
      expose:
        - 5432
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      networks:
        - default
      logging:
        driver: "json-file"
        options:
          max-size: "50m"
          max-file: "5"
          compress: "true"

    web:
      build: .
      command: ["gunicorn","-b", "0.0.0.0:8001", "-w", "4", "-k", "gevent", "--worker-tmp-dir", "/dev/shm", "app:app"]
      volumes:
        - static_volume:/app/staticfiles
        - uploads:/app/media_uploads
      expose:
        - 8001
      depends_on:
        - db
      env_file:
        - ./.env
      entrypoint:
        - "./docker-entrypoint.sh"
      networks:
        - default
      logging:
        driver: "json-file"
        options:
          max-size: "50m"
          max-file: "5"
          compress: "true"

    nginx:
      build: ./service/nginx
      volumes:
        - static_volume:/app/staticfiles
        - uploads:/app/media_uploads
      expose:
        - 8002
      depends_on:
        - web
      env_file:
        - ./.env
      environment:
        - VIRTUAL_PORT=8002
      networks:
        - default
        - nginx-gateway
      logging:
        driver: "json-file"
        options:
          max-size: "50m"
          max-file: "5"
          compress: "true"

  networks:
    default:
    nginx-gateway:
        external:
          name: nginx-gateway

  volumes:
    postgres_data:
    static_volume:
    uploads:
    code:
